on:
  push:
    branches: [ main ]

jobs:
  build-page:
    runs-on: ubuntu-latest
    name: Build page
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        run: |
          curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
          sudo apt-get install -y nodejs
          npm --version

      - name: Install JDK
        run: |
          sudo apt-get install openjdk-11-jdk-headless
          javac -version

      - name: Compile CLJS
        run: |
          npm install
          npx shadow-cljs release app

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "generate JS"
          file_pattern: docs/js/app.js docs/js/manifest.edn
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}         
